name: panorama_notebook
channels:
  - bioconda
  - conda-forge
dependencies:
  - pandas>=2.2.3,<3.0
  - ipykernel>=6.29.5
  - jupyter>=1.1.1
  - tqdm>=4.67.1
  - seaborn>=0.13.2
  - networkx>=3.4.2
  - colorcet>=3.1.0
  - upsetplot>=0.9.0
  - genome_updater>=0.6.4